# Generated by Django 4.2.20 on 2025-03-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alunos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=255)),
                ("email", models.CharField(default="", max_length=255, unique=True)),
                ("telefone", models.CharField(default="", max_length=18)),
            ],
            options={
                "db_table": "alunos",
            },
        ),
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=255)),
                ("descricao", models.TextField()),
                ("carga_horaria", models.IntegerField()),
                ("instrutor", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "cursos",
            },
        ),
        migrations.CreateModel(
            name="Inscricoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alunos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.alunos",
                    ),
                ),
                (
                    "cursos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.cursos",
                    ),
                ),
            ],
            options={
                "db_table": "inscricoes",
                "unique_together": {("cursos", "alunos")},
            },
        ),
    ]
