# Generated by Django 5.1.7 on 2025-03-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_administrador_alter_inscricoes_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255, unique=True)),
                ('telefone', models.CharField(default='', max_length=18, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('aluno', 'Aluno')], default='', max_length=20)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.RemoveField(
            model_name='inscricoes',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='senha',
        ),
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='telefone',
            field=models.CharField(default='', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('aluno', 'Aluno')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='aluno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='website.aluno'),
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
