# Generated by Django 5.1.7 on 2025-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aluno_remove_inscricoes_alunos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='senha',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(default='', max_length=30),
        ),
    ]
