# Generated by Django 5.1.7 on 2025-03-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_administrador_senha_aluno_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.AddField(
            model_name='administrador',
            name='_senha',
            field=models.CharField(default='', editable='false', max_length=255),
        ),
        migrations.AddField(
            model_name='aluno',
            name='_senha',
            field=models.CharField(default='', editable='false', max_length=255),
        ),
    ]
