# Generated by Django 5.1.7 on 2025-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_administrador_senha_remove_aluno_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='_senha',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='_senha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
