# Generated by Django 5.1.7 on 2025-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename__senha_administrador_senha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.AddField(
            model_name='administrador',
            name='_senha',
            field=models.CharField(default='', editable='false', max_length=255),
        ),
        migrations.AddField(
            model_name='aluno',
            name='_senha',
            field=models.CharField(default='', editable='false', max_length=255),
        ),
    ]
