-- MySQL Script generated by MySQL Workbench
-- Tue Mar 18 17:37:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_crud_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_crud_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_crud_schema` DEFAULT CHARACTER SET utf8 ;
USE `db_crud_schema` ;

-- -----------------------------------------------------
-- Table `db_crud_schema`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_crud_schema`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `carga_horaria` INT NOT NULL,
  `instrutor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_crud_schema`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_crud_schema`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_crud_schema`.`inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_crud_schema`.`inscricoes` (
  `cursos_id` INT NOT NULL,
  `alunos_id` INT NOT NULL,
  PRIMARY KEY (`cursos_id`, `alunos_id`),
  INDEX `fk_inscricoes_alunos1_idx` (`alunos_id` ASC) VISIBLE,
  INDEX `fk_inscricoes_cursos_idx` (`cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_inscricoes_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `db_crud_schema`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricoes_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `db_crud_schema`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_crud_schema`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_crud_schema`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
